[project]
name = "e3j"
version = "0.1.0b1"
description = "Fast Euclid equivariant operations for JAX"
authors = [
    { name="Olivier Peltre", email="o.peltre@instadeep.com" },
    { name="Armand Picard", email="a.picard@instadeep.com" },
    { name="Adrien Pichard", email="a.pichard@instadeep.com" }
]
license = {text="Apache-2.0"}
license-files = ["LICENSE"]
readme = "README.md"
requires-python = ">=3.11,<3.15"
dependencies = [
    "numpy >= 1.26.4",
    "jax >= 0.6.2",
    "gitpython ~= 3.1.43",
    "e3nn-jax >= 0.20.6",
    "flax ~= 0.12.0",
    "pandas ~= 2.2.2",
    "matplotlib >= 3.9.0",
    "setuptools ~= 75.8.0"
]

[project.optional-dependencies]
ops = [
    "e3j_ops == 0.1.0b1",
    "pybind11 >= 2.13.6"
]

[dependency-groups]
cuda_local = [
    "jax[cuda12_local] >= 0.6.2",
    "jaxlib >= 0.6.2"
]
cuda13_local = [
    "jax[cuda13_local] >= 0.6.2",
    "jaxlib >= 0.6.2"
]
cuda = [
    "jax[cuda12] >= 0.6.2",
    "jaxlib >= 0.6.2"
]
cuda13 = [
    "jax[cuda13] >= 0.6.2",
    "jaxlib >= 0.6.2"
]
cpu = [
    "jax[cpu] >= 0.6.2",
    "jaxlib >= 0.6.2"
]

dev = [
    "pytest == 8.3.2",
    "pytest-cov == 5.0.0",
    "seaborn == 0.13.2",
    "pre-commit == 3.7.1",
    "pybind11 >= 2.13.6",
    "wheel ~= 0.45.1"
]

docs = [
    "sphinx == 8.0.2",
    "sphinx-math-dollar ~= 1.2.1",
    "furo >= 2024.8.6"
]

[tool.uv]
default-groups = ["dev"]

[tool.uv.sources]
e3j_ops = {workspace = true}

[tool.uv.workspace]
members = ["lib/*"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
