[pytest]
testpaths = tests
addopts = -m "not e3j_ops and not mosaic_tpu"
env =
    JAX_DEFAULT_MATMUL_PRECISION=highest
markers =
    slow
    tolerated: passing with high tolerance only
    e3j_ops: build and run requires GPU
    mosaic_tpu: run require TPU
