formats:
  - svg
  - png

palette:
  e3x: "#38f"
  e3nn: "#3aa"
  e3nn_f32: "#288"
  e3j: "#a48"
  e3j_float32: "#f49"
  e3j_ops_leading: "#f49"
  e3j_ops: "#f3c"
  e3nn_torch: "#e53"
  torch_cuet: "#3fa"
  cuequivariance_jax: "#3fa"
  torch_openeq: "#2d9"
  jax_builtin: "#222"

modules:
  LinearBenchmark:
    skip: True
    grid:
      l_max: [2, 4, 6]
      mul: [32, 128]
      batch_size: [128, 256, 512, 1024, 2048]
      n_it: [500]

    seaborn:
      style: mul

    log_xy: True

  HarmonicsBenchmark:
    skip: True
    grid:
      batch_size: [
        512, 1024, 2048, 4096,
        8192, 16384, 65536, 131072,
      ]
      l_max: [3, 6, 8]
      n_it: [500]

    log_xy: True

  HarmonicsGradBenchmark:
    skip: True
    grid:
      l_max: [3, 6, 8]
      batch_size: [
        512, 1024, 2048, 4096,
        8192, 16384, 65536, 131072,
      ]
      n_it: [500]

    log_xy: True

  TensorProductBenchmark:
    skip: False

    grid:
      l_max: [2, 3]
      mul: [32, 64, 128]
      batch_size: [
        1024, 4096, 8192,
        16384, 65536,
        131072, 262144,
      ]
      n_it: [200]

    log_xy: True

    seaborn:
      style: mul

  TensorProductGradBenchmark:
    skip: False

    grid:
      l_max: [2, 3]
      mul: [32, 64, 128]
      batch_size: [
        256, 1024,
        4096, 16384,
        65536, 131072,
      ]
      n_it: [200]

    log_xy: True

    seaborn:
      style: mul


  SymmetricContractionBenchmark:
    skip: False

    grid:
      l_max: [3]
      l_max_out: [1]    # a.k.a. node_symmetry
      correlation: [2, 3]
      num_channels: [64, 128]
      num_species: [10]
      batch_size: [256, 512, 1024]
      n_it: [100]

    log_xy: True

    seaborn:
      col: correlation
      style: num_channels

  SymmetricContractionGradBenchmark:
    skip: True

    grid:
      l_max: [2, 3]
      l_max_out: [1]    # a.k.a. node_symmetry
      correlation: [3]
      num_channels: [64]
      num_species: [10]
      batch_size: [256, 512, 1024]
      n_it: [100]

    log_xy: True

grid-defaults:
  batch_size: [256, 512, 1024]
  n_it: [100]
