formats:
  - png
  - svg

palette:
  e3x: "#38f"
  e3nn: "#3aa"
  e3j: "#a48"
  e3j_float32: "#f49"
  e3j_ops: "#f49"
  torch_cuet: "#3fa"

modules:
  LinearBenchmark:
    skip: True
    grid:
      l_max: [2]
      mul: [32]
      batch_size: [1024]
      n_it: [100]

    seaborn:
      style: mul

    log_xy: True

  HarmonicsBenchmark:
    skip: False
    grid:
      batch_size: [1024]
      l_max: [3]
      n_it: [100]

    log_xy: True

  HarmonicsGradBenchmark:
    skip: False
    grid:
      l_max: [3]
      batch_size: [1024]
      n_it: [100]

    log_xy: True

  TensorProductBenchmark:
    skip: False

    grid:
      l_max: [3]
      batch_size: [1024]
      n_it: [100]

    log_xy: True

  TensorProductGradBenchmark:
    skip: False

    grid:
      l_max: [3]
      batch_size: [1024]
      n_it: [500]

    log_xy: True


  SymmetricContractionBenchmark:
    skip: True

    grid:
      l_max: [3]
      correlation: [3]
      num_channels: [32]
      num_species: [10]
      batch_size: [1024]
      n_it: [100]

    log_xy: True

  SymmetricContractionGradBenchmark:
    skip: True

    grid:
      l_max: [3]
      correlation: [3]
      num_channels: [32]
      num_species: [10]
      batch_size: [1024]
      n_it: [100]

    log_xy: True

grid-defaults:
  batch_size: [256, 512, 1024]
  n_it: [100]
