# Copyright (c) 2026 InstaDeep Ltd
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

name: Tests and Linters 🧪

on:
  push:
    branches: [main]
  pull_request:

permissions:
  contents: read

jobs:
  linters:
    runs-on: ubuntu-latest
    container:
       image: python:3.11-slim
    steps:
      - name: setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          gcc \
          git
          git config --system --add safe.directory $GITHUB_WORKSPACE

      - name: checkout code 📦
        uses: actions/checkout@v5

      - name: install uv
        uses: astral-sh/setup-uv@v7

      - name: setup env
        run: uv sync --no-install-project --group dev --group docs --frozen

      - name: run linters 🖌️
        run: |
          git init
          uv run --no-sync pre-commit run --all-files --verbose

  tests:
    runs-on: ubuntu-latest
    container:
       image: python:3.11-slim
    steps:
      - name: setup
        run: |
          apt-get update && apt-get install -y \
          coreutils \
          git

      - name: checkout code 📂
        uses: actions/checkout@v5

      - name: install uv
        uses: astral-sh/setup-uv@v7

      - name: setup env
        run: uv sync --group dev --group docs --frozen

      - name: run tests 🧪
        run: |
          uv run --no-sync pytest --cov=e3j --verbose tests/
